config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/pictures/show', to: 'pictures#show'
  get '/users/current', to: 'users#current'

  resource :users
  resource :pictures
  resource :session, only: [:new, :create, :destroy]
end

app/models/caption.rb
class Caption < ActiveRecord::Base
	belongs_to :search
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :search
end

app/models/search.rb
class Search < ActiveRecord::Base
	has_many :pictures
	has_many :captions

	# before_create :fetch_results

	# def fetch_results
	# 	results = instagram.tag_recent_media(keyword)
	# 	# binding.pry
	# 	results.each do |result|
	# 		self.pictures << Picture.new {
	# 			url: result.images.standard_resolution
	# 		}
	# 	end
	# end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	return nil unless session[:session_token]
  	@current_user ||= User.find_by(session_token: session[:session_token])
  end

  private

  def login!(user)
  	return nil unless session[:session_token]
  	@current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
  	current_user.update(session_token: nil)
  	session[:session_token] = make_token
  end

  def make_token
  	return SecureRandom.urlsafe_base64
  end

  def require_current_user
  	redirect_to new_session_url unless current_user
  end
end

app/controllers/captions_controller.rb
class CaptionsController < ApplicationController
	def configure_twitter
		client = Twitter::REST::Client.new do |config|
			config.consumer_key = "pu4D6ohzf9yG8XlM9hpJFAGWr"
			config.consumer_secret = "LNIimgn64o4jWpCgW3yNMLDoctjq4P8JvGU6L0sc33UuiRh6eZ"
			config.access_token = "43109004-OW0dzDk1SyzW07VmLlUhyAcPfi9IhhdOfReerUA8s"
			config.access_token_secret = "B7fQOSnL5R765OxWlOmYAlGN4p3uZcNaOiWokHyey7YLX"
		end
		@twitter_client = client
	end

	def fetch_results
		@captions_array = []
		@data_array = []
		@results.each do |result|
			@pictures_array << Caption.create!(
				:text => result.images.standard_resolution.url, 
				:contributor => result.user[:username]
			)
		end

		@pictures_array.map do |pic|
			@data_array << {url: pic.url}
		end
	end

	def create
		self.configure_twitter

		hashtag = "#"
		@results = @client.search("#{hashtag}#{params[:keyword]}")
		self.fetch_results
		
		respond_to do |format|
			format.json {render json: @data_array}
		end
	end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def configure_instagram
		Instagram.configure do |config|
			config.client_id = ENV["_FIGARO_instagram_client_id"] || ENV["instagram_client_id"]
			config.client_secret = ENV["_FIGARO_instagram_client_secret"] || ENV["instagram_client_secret"]
			@instagram_client = Instagram.client
		end
	end

	def configure_twitter
		client = Twitter::REST::Client.new do |config|
			config.consumer_key = "pu4D6ohzf9yG8XlM9hpJFAGWr"
			config.consumer_secret = "LNIimgn64o4jWpCgW3yNMLDoctjq4P8JvGU6L0sc33UuiRh6eZ"
			config.access_token = "43109004-OW0dzDk1SyzW07VmLlUhyAcPfi9IhhdOfReerUA8s"
			config.access_token_secret = "B7fQOSnL5R765OxWlOmYAlGN4p3uZcNaOiWokHyey7YLX"
		end
		@twitter_client = client
	end

	def generate_default
		@defaults = ["sunset", "nyc", "la", "london", "paris", "tokyo", "caribbean", "worldnews", "sunrise", "mountain", "landscape", "newyork", "sky", "clouds", "music", "forest", "river", "ocean", "carniva", "politics", "bbq", "food", "parade", "holiday", "technology", "tech", "dog", "dogs", "nature", "happy", "cinema", "movies", "redcarpet", "blue", "red", "yellow", "sun", "museum", "football", "art"]
		@default = @defaults.sample
	end

	def fetch_instagram_results
		@pictures_array = []
		@data_array = []
		@instagram_results.each do |result|
			@pictures_array << Picture.create!(
				:url => result.images.standard_resolution.url,
				:contributor => result.user[:username]
			)
		end

		@pictures_array.map do |pic|
			@data_array << {url: pic.url}
		end
	end

	def create_instagram
		self.configure_instagram

		@instagram_results = @instagram_client.tag_recent_media(params[:keyword])
		self.fetch_instagram_results

		respond_to do |format|
			format.json {render json: @data_array}
		end
	end

	def show_instagram
		self.generate_default
		self.configure_instagram

		@instagram_results = @instagram_client.tag_recent_media(@default)
		self.fetch_instagram_results


		respond_to do |format|
			format.html
			format.json {render json: @data_array}
		end
	end

	def create
		self.create_instagram
		#self.create_twitter
	end

	def show
		self.show_instagram
		#self.show_twitter
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_current_user, only: :destroy

  def new
  	@user = User.new
  end

  def create
  	@user = User.find_by(username: session_params[:username])

  	if @user && @user.authenticate(session_params[:password])
  		login!(@user)

  		redirect_to pictures_show_url
  	else
  		redirect_to new_session_url, alert: "Username and/or password incorrect" #add error message?
  	end
  end

  def destroy
  	logout!

  	redirect_to new_session_url
  end

  private

  def session_params
  	@session_params ||= params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_is_current_user, only: [:edit, :update]

  def current
    respond_to do |format|
      format.json { render json: {
          id: current_user.id,
          username: current_user.username
        }
      }
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to new_session_url
  	else
  		render :new
  	end
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = current_user
  	
  	if @user.authenticate(params[:user][:current_password])
  		@user.update(password_params)

  		redierct_to user_contacts_url(@user)
  	else
  		render :edit
  	end
  end

  private
  
  def user_params
  	params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def password_params
  	params.require(:user).permit(:password, :password_confirmation)
  end

  def user_is_current_user
  	uesr = User.find(params[:id])

  	if current_user
  		redirect_to user_contact_path(current_user) unless user == current_user
  	else
  		redirect_to new_session_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captions_helper.rb
module CaptionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Captionous</title>
  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/show.html.erb
<body>

  <!-- Navbar -->

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>

     <a class="main-logo pull-left" href="#" alt="CAPTIONOUS"><img src="http://www.ninebranches.com/nb/wp-content/uploads/2015/03/main-logo.png"></a>
     <div class="collapse navbar-collapse">

       <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="#">HOME</a></li>
          <!-- <li><a href="#">REGISTER</a></li>
          <li><a href="#">SIGN UP</a></li> -->
          <li>
            <%= link_to "LOG OUT", session_url, method: "delete" %>
          </li>
          <li>
            <%= link_to "PASSWORD", edit_users_url(@current_user) %>
          </li>
        </ul>

      </div>
    </div>
  </div>

  <!-- End navbar -->

  <!-- Jumbotron -->
  <div id="myCarousel" class="jumbotron">
    <div class="container">
      <div class="carousel-inner">
        <div class="item active">
          <h1>YOUR WORLD IN CONTEXT.</h1>
          <!-- <p class="lead">Search bar goes below.</p>
          <p>
            <a class="btn btn-default btn-lg" href="#">Something something</a>
            <a class="btn btn-default btn-lg" data-toggle="modal" href="#textModal" >Yes, yes, I'd like some more</a>
          </p> -->
        </div>
        <!-- Search form -->
        <!-- <div class="searchbar">
          <form id='search'>
            <input id="search-picture-keyword" type="text" placeholder="ENTER KEYWORD" name="picture[keyword]">
            <i class="fa fa-search fa-3x"></i>
            <input class="button orange" type="submit" value="Find It!">
          </form>
        </div> -->

        <div class="searchbar">

          <form id="search">
            <input id="search-picture-keyword" type="text" placeholder="ENTER KEYWORD" name="picture[keyword]">
            <button class="btn btn-submit" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </form>
        </div>

        <!-- End search form -->
      </div>
    </div>
  </div>

  <!-- End jumbotron -->




  <!-- Modal -->
  <div class="modal fade" id="textModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">KEEP GETTING THE BIG PICTURE</h4>
        </div>
        <div class="modal-body">
          <form class="form-inline">
            <div class="form-group">
              <label class="sr-only" for="mobilePhone">EMAIL</label>
              <input type="tel" class="form-control" id="mobilePhone" placeholder="email">
            </div>
            <button type="submit" class="btn btn-primary" data-dismiss="modal">Send me link</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- End modal -->


  <div class="container">

    <div="row">
    <div class="col-xs-6">
      <i class="fa fa-instagram fa-5x"></i>
      <div id="results"></div>
    </div>
      <div class="col-xs-6">
        <i class="fa fa-twitter fa-5x"></i>
      </div>

  </div>

<!-- <%= yield %> -->

  <br />
  <br />
  <br />
  <br />
  <br />
  <br />


  <div class="row">
    <div class="col-xs-12">
      <p>&copy; 2015 Captionous — by VelocirAPPtor, Inc. All rights reserved.</p>
    </div>
  </div>

</body>

app/views/users/edit.html.erb
<main class="gateway">
<h1>Change your password</h1>

<%= form_for @user do |f| %>
  <%= password_field_tag "user[current_password]", nil, placeholder: "current password" %>
  <br/>
  <%= f.password_field :password, placeholder: "new password" %>
  <br/>
  <%= f.password_field :password_confirmation, placeholder: "confirm new password" %>
  <br/>

  <%= f.submit "Update password" %>
<% end %>
</main>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :username, placeholder: "desired username" %>
  <br/>
  <%= f.password_field :password, placeholder: "password" %>
  <br/>
  <%= f.password_field :password_confirmation, placeholder: "confirm password" %>
  <br/>

  <%= f.submit "Sign up!" %>
<% end %>

<a href ="../../../../../">Login screen</a>